### ISSUE TITLE
Sprint 3 review

### ISSUE THREAD

**Issue by nep2ne** [are-you-still-watching/web-app#32]
So far we have created the basic patterns we will need to code our website, including banners, buttons, cards, a header and footer, a navigation menu.

@thomasjbradley

**Comment by nep2ne** [comment]
What worked well is that the Wireframes were well built and easy to understand. I had a really hard time with the banners patterns. We worked on them together as a team in class. Our steps / process for creating branches and working within the Pattern Library structure needs to be ironed out before we move forward.

**Comment by KyleVBP** [comment]
I succeeded well in making my cards, creating them was a quick and positive experience. There was some code that wasn't working for me but it wasn't a big aspect of the cards. And our team had some issues on the process of creating and working in separate branches.

**Comment by moutonrebelle** [comment]
We succeeded at making patterns. I created the icons and buttons and although we had some issues with creating branches, we were able to communicate and fix the problems we encountered. Wireframes were easy to understand so it was a big "plus" when creating patterns.

**Comment by Sebby-T** [comment]
What succeeded in this sprint for me was creating all possible navigations for our website and then combining those patterns to create the header and footer patterns for the website.  Minor issues came up with coding from teammates but they made their concerns known and we worked as a team to help them with their issues.

**Comment by thomasjbradley** [comment]
👍
