### ISSUE TITLE
Sprint 5 review

### ISSUE THREAD

**Issue by nep2ne** [are-you-still-watching/web-app#63]
This week, we created a profile page banner, created our Index file using the pattern library, finalized our card layout, and finalized our buttons design. @thomasjbradley

**Comment by nep2ne** [comment]
This week, I created the Profile page banner, and I made my code variable (all banners). I didn't encounter any issues with the coding or with the collaboration.

**Comment by moutonrebelle** [comment]
This week, I have made the subscription buttons but I did struggle making them. I will fix them this week. Collaboration went well.

**Comment by KyleVBP** [comment]
This week I worked on making the cards I've been working on variable. Something happened to my cards while working on it and the hover state stopped working, I couldn't find a fix, but this week we are working on updating the style of the cards and the current hover will no longer be needed.

**Comment by Sebby-T** [comment]
This week I created the layout for the index page and coded the card to be variable. I improved and reduced code where I could to make the card more efficient.  I attempted to resolve issues where possible and succeded. I found this sprint mostly successful.

**Comment by thomasjbradley** [comment]
:neckbeard:
